# Generated by Django 2.2.4 on 2019-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_log', '0002_auto_20190928_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='base_color',
            field=models.CharField(default='gray', max_length=15),
        ),
    ]
